[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
my_election_project = "6RfNNTCAWnVgPspEkv5So37oMEyQpqfgdnH9EevYjfvW"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"
rpc-port = 8900

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
